# Generated by Django 5.0.2 on 2024-05-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='My_Users',
        ),
    ]
