# Generated by Django 5.0.2 on 2024-05-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_rename_users_my_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_users',
            name='username',
            field=models.CharField(default='no-username', max_length=100),
        ),
    ]
