# Generated by Django 5.0.2 on 2024-05-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_my_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_users',
            name='password',
            field=models.CharField(default='no-password', max_length=100),
        ),
        migrations.AlterField(
            model_name='my_users',
            name='email',
            field=models.CharField(default='no-email', max_length=100),
        ),
    ]
